Cargo: pin sysinfo to 0.36
Pin sysinfo to =0.36 for MSRV issues with Rust < 1.85.0. This should be
unpinned around 2026-02-17 if we continue with our ~1 year MSRV policy

Without the pinning, CI with Rust 1.81 fails like:

```
  Downloaded sysinfo v0.37.0
error: failed to parse manifest at `/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sysinfo-0.37.0/Cargo.toml`

Caused by:
  feature `edition2024` is required

  The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.81.0 (eeb90cda1 2024-09-04)).
  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature.
Error: Process completed with exit code 101.
```

Signed-off-by: Dongsu Park <dpark@linux.microsoft.com>