Cargo: fix clippy errors around litemap 0.7.5 and zerofrom 0.1.6
Avoid clippy errors from MSRV requirement 1.81 of litemap 0.7.5
as well as zerofrom 0.1.6.
Needed because azure-init CI still requires Rust 1.76+.

```
error: package `litemap v0.7.5` cannot be built because it requires rustc 1.81 or newer, while the currently active rustc version is 1.76.0
error: package `zerofrom v0.1.6` cannot be built because it requires rustc 1.81 or newer, while the currently active rustc version is 1.76.0
```