error: include the underlying error in the error text
While these may not be the optimal error messages in all cases, this
should make them more useful by including the underlying error message
so that you get, for example, "HTTP client error occurred: HTTP status
client error (405 Method Not Allowed) for url (http://127.0.0.1:35195/)"
instead of "HTTP client error ocurred".