libazureinit: fix redundant clone issue of clippy
Now that CI needs to build source code with an old version 12 months
ago, Rust 1.70, cargo clippy starts to print out warnings like below.

```
error: redundant clone
  --> libazureinit/src/distro.rs:21:35
   |
21 |                     .arg(home_path.clone())
   |                                   ^^^^^^^^ help: remove this
   |
note: this value is dropped without further use
  --> libazureinit/src/distro.rs:21:26
   |
21 |                     .arg(home_path.clone())
   |                          ^^^^^^^^^
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_clone
   = note: `-D clippy::redundant-clone` implied by `-D warnings`
error: redundant clone
```

Fix redundant clone issue of clippy.