.github: migrate to dtolnay/rust-toolchain to build with old toolchains (#94)
* .github: migrate to dtolnay/rust-toolchain

Migrate to GitHub Actions dtolnay/rust-toolchain, to support multiple
toolchains as well as an old toolchain like stable 12 months ago.

Note: it is not possible to go back to 18 months ago, Rust 1.66.1 as of
now, because then nix v0.29.0 of the current code base cannot be built,
nix 0.29.0 requires rustc 1.69 or newer.

* libazureinit: fix redundant clone issue of clippy

Now that CI needs to build source code with an old version 12 months
ago, Rust 1.70, cargo clippy starts to print out warnings like below.

```
error: redundant clone
  --> libazureinit/src/distro.rs:21:35
   |
21 |                     .arg(home_path.clone())
   |                                   ^^^^^^^^ help: remove this
   |
note: this value is dropped without further use
  --> libazureinit/src/distro.rs:21:26
   |
21 |                     .arg(home_path.clone())
   |                          ^^^^^^^^^
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_clone
   = note: `-D clippy::redundant-clone` implied by `-D warnings`
error: redundant clone
```

Fix redundant clone issue of clippy.